name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake
    - name: Build
      run: make
    - name: Test_Utilities
      run: make test_utilities
    - name: Test_UDP
      run: make test_udp_sockets
    - name: Test_Network_Builder
      run: make test_network_builder
    - name: Test_Reinforcement_Learning
      run: make test_reinforcement_learning
    - name: Test_Aplysia
      run: make test_aplysia